version: '2'

networks:
  pghigh_network:
    driver: bridge
services:
  pg-0:
    image: bitnami/postgresql-repmgr:14
    ports:
      - 5432
    volumes:
      - ./pg_0_data:/bitnami/postgresql
    env_file:
      - ./pg-0.env
  pg-1:
    image: bitnami/postgresql-repmgr:14
    ports:
      - 5432
    volumes:
      - ./pg_1_data:/bitnami/postgresql
    env_file:
      - ./pg-1.env
#    depends_on:
#     - pg-0
  pgpool:
    image: bitnami/pgpool:4
    ports:
      - 5432:5432
    env_file:
      - ./pg-pool.env
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - pg-0

  pgadmin:
    image: dpage/pgadmin4:latest 
    container_name: postgres-adm
    restart: always
    ports:
      - 5050:80
    environment:
      TZ: "Europe/Madrid"
    logging:
      driver: json-file
    env_file:
      - ./pgadmin.env
    #volumes:
    #  - ./pgadmin/pgadmin_servers.json:/pgadmin4/servers.json
    depends_on:
      - pgpool
    networks:
      - pghigh_network
